apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: username-lll-deployed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Reploy-Plateforme/username-lll-deployed
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: username-lll-deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
